# Generated by Django 5.1.1 on 2025-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Message', models.TextField(max_length=200)),
            ],
        ),
    ]
